// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAxiaMarket.Data;

namespace MyAxiaMarket.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220531151916_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("MyAxiaMarket.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArticle");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("MyAxiaMarket.Models.Boutique", b =>
                {
                    b.Property<int>("IdBoutique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NatureBoutique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomBoutique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBoutique");

                    b.ToTable("Boutiques");
                });

            modelBuilder.Entity("MyAxiaMarket.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategorie");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyAxiaMarket.Models.Personne", b =>
                {
                    b.Property<int>("IdP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdresseP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotPassP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelephoneP")
                        .HasColumnType("int");

                    b.HasKey("IdP");

                    b.ToTable("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
