// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAxiaMarket.Data;

namespace MyAxiaMarket.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220331173142_initialcreate1")]
    partial class initialcreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyAxiaMarket.Models.Personne", b =>
                {
                    b.Property<int>("IdP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdresseP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotPassP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelephoneP")
                        .HasColumnType("int");

                    b.HasKey("IdP");

                    b.ToTable("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
